spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #운영환경의 log는 모두 logging을 통해서 실행해야됨
        format_sql: true
        default_batch_fetch_size : 100
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug

#하이버네이트의 모든 SQL이 다 보이게됨

