#/api/members/spring 정상작동

GET http://localhost:8080/api/members/spring
Content-Type: application/json

###
#예외 발생 - ex입력 - json
GET http://localhost:8080/api/members/ex
Accept: application/json

###
#예외 발생 - ex입력 - api
GET http://localhost:8080/api/members/ex
Accept: text/html